MvcProjeKampi/Controllers/AuthorizationController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class AuthorizationController : Controller
    {
        AdminManager adminmanager = new AdminManager(new EfAdminDal());
        RoleManager roleManager = new RoleManager(new EfRoleDal());
        Context _context = new Context();
        // GET: Authorization
        public ActionResult Index()
        {
            var adminvalues = adminmanager.GetList();
            return View(adminvalues);
        }

        [HttpGet]
        public ActionResult EditAdmin(int id)
        {
            List<SelectListItem> valueadminrole = (from c in roleManager.GetRoles()
                                                   select new SelectListItem
                                                   {
                                                       Text = c.RoleName,
                                                       Value = c.RoleId.ToString()

                                                   }).ToList();

            ViewBag.valueadmin = valueadminrole;

            var adminvalue = adminmanager.GetById(id);
            return View(adminvalue);
        }
        [HttpPost]
        public ActionResult EditAdmin(Admin admin)
        {
            admin.AdminStatus = true;
            adminmanager.AdminUpdate(admin);
            return RedirectToAction("Index");
        }
        public ActionResult AktifveyaPasifDurum(int id)
        {
            var adminValue = adminmanager.GetById(id);

            if (adminValue.AdminStatus == true)
            {
                adminValue.AdminStatus = false;
            }
            else
            {
                adminValue.AdminStatus = true;
            }
            adminmanager.AdminUpdate(adminValue);
            return RedirectToAction("Index");
        }
    }
}

MvcProjeKampi/Views/Authorization/EditAdmin.cshtml
@model EntityLayer.Concrete.Admin

@{
    ViewBag.Title = "EditAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Admin Güncelleme Sayfası</h2>
@using (Html.BeginForm("EditAdmin", "Authorization", FormMethod.Post))
{

    <div class="form-group">
        @Html.HiddenFor(c => c.AdminID, new { @class = "form-control" })
        @Html.HiddenFor(c => c.AdminPassword, new { @class = "form-control" })
        @Html.HiddenFor(c => c.AdminUserName, new { @class = "form-control" })
        <br />
        @Html.Label("Admin Kullanıcı Adı")
        @Html.TextBoxFor(c => c.AdminUserName, new { @class = "form-control" })
        <br />
        @Html.Label("Rol")
        @Html.DropDownListFor(c => c.RoleId, (List<SelectListItem>)ViewBag.valueadmin, new { @class = "form-control" })
        <br />

        <button class="btn btn-success">Güncelle</button>


    </div>

    @*<div class="form-group">
            @Html.HiddenFor(x => x.AdminID, new { @class = "form-control" })
            @Html.Label("Admin Kullanıcı Adı")
            @Html.TextBoxFor(x => x.AdminUserName, new { @class = "form-control" })
            <br />
            @Html.Label("Admin Şifresi")
            @Html.TextAreaFor(x => x.AdminPassword, new { @class = "form-control" })
            <br />
            @Html.Label("Admin Rolü")
            @Html.DropDownListFor(x => x.AdminID, (List<SelectListItem>)ViewBag.adm, new { @class = "form-control" })
            <br />
            <button class="btn btn-outline-success" id="btn1">Güncelle</button>
        </div>
        <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
        <script>
            $('#btn1').click(function () {
                swal("Tebrikler!", "Ekleme işlemi başarılı bir şekilde gerçekleşti!", "success");
            })
        </script>
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>*@
}

MvcProjeKampi/Views/Authorization/Index.cshtml
@using EntityLayer.Concrete
@model List<Admin>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{ string status = "";}
@{ string statusButton = "";}
<br />
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Admin Kullanıcı Adı</th>
        <th>YETKİ</th>
        <th>Aktif/PASİF YAP</th>
        <th>YETKİSİNİ DEĞİŞTİR</th>
    </tr>
    @foreach (var item in Model)
    {
        if (item.AdminStatus == true)
        {
            status = "Pasif Yap";
        }
        if (item.AdminStatus == false)
        {
            status = "Aktif Yap";
        }
        if (item.AdminStatus == true)
        {
            statusButton = "btn btn-danger";
        }
        if (item.AdminStatus == false)
        {
            statusButton = "btn btn-warning";
        }
<tr>
    <th>@item.AdminID</th>
    <td>@item.AdminUserName</td>
    <td>@item.Role.RoleName</td>
    <td><a href="/Authorization/AktifveyaPasifDurum/@item.AdminID" class="@statusButton">@status</a></td>
    <td><a href="/Authorization/EditAdmin/@item.AdminID" class="btn btn-warning">Yetkisini Değiştir</a></td>
</tr>
    }
</table>
<a href="/Register/Index/" class="btn btn-dark">Yeni Admin Ekle</a>
<script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>